### ISSUE TITLE
Replace "flag" with Cobra 

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/summaraizer#7]
See https://pkg.go.dev/github.com/spf13/cobra

It's more modern and should also help with #6

**Comment by chb-ioki** [comment]
We could also go with [Viper](https://github.com/spf13/viper) which goes even a bit further e.g. regarding convenience of configuration

**Comment by chb-ioki** [comment]
ah - seems like I am a little late 😅

**Comment by StefMa** [comment]
I wasn't aware of `Viper`.
However, I guess those are different projects. Viper (or Cobra) is not a replacement for Cobra (or Viper).
Cobra is more like for CLI flags and command handling, while Viper is more for configuration handling.
However, probably both worke nice together so we could use `Viper` to read a configuration put in as a `Cobra` command... 

I guess something like this would make sense 🤔

**Comment by chb-ioki** [comment]
You are correct!

It is even stated in the [cobra README](https://github.com/spf13/cobra):

> Optional seamless integration with [viper](https://github.com/spf13/viper) for 12-factor apps
